# Generated by Django 4.1.7 on 2023-04-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialTravel', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
