# Generated by Django 4.1.7 on 2023-04-17 15:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SocialTravel', '0006_alter_profile_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='creado_el',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
